backend:
  name: github
  repo: jschuler/patternfly-next
media_folder: static/assets/images
public_folder: /img
base:
  fields: &ref_0
    - label: Template Key
      name: templateKey
      widget: hidden
      default: about-page
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: markdown
collections:
  - name: pages
    label: Pages
    files:
      - file: src/site/pages/accessibility-guide.md
        label: Accessibility
        name: accessibility
        fields: *ref_0
      - file: src/site/pages/contribution.md
        label: Contribution
        name: contribution
        fields: *ref_0
  - name: components
    label: Components
    files:
      - file: src/patternfly/components/Alert/docs/code.md
        label: Alert
        name: alert
        fields: *ref_0
      - file: src/patternfly/components/Backdrop/docs/code.md
        label: Backdrop
        name: backdrop
        fields: *ref_0
      - file: src/patternfly/components/Box/docs/code.md
        label: Box
        name: box
        fields: *ref_0
      - file: src/patternfly/components/MyComponent/docs/code.md
        label: MyComponent
        name: MyComponent
        fields: *ref_0
      - file: src/patternfly/components/HolyMoly/docs/code.md
        label: HolyMoly
        name: HolyMoly
        fields: *ref_0
      - file: src/patternfly/components/SweetComponent/docs/code.md
        label: SweetComponent
        name: SweetComponent
        fields: *ref_0
      - file: src/patternfly/components/SweetComponent2/docs/code.md
        label: SweetComponent2
        name: SweetComponent2
        fields: *ref_0
      - file: src/patternfly/components/SweetComponent3/docs/code.md
        label: SweetComponent3
        name: SweetComponent3
        fields: *ref_0
